Update auditwheel command to use --exclude (#83)
The internal structure of auditwheel has changed with the 6.0.0 release, causing our current script to break:

```
Traceback (most recent call last):
  File "//auditwheel-keep-pyarrow.py", line 4, in <module>
    from auditwheel.policy import _POLICIES
ImportError: cannot import name '_POLICIES' from 'auditwheel.policy' (/usr/local/lib/python3.10/site-packages/auditwheel/policy/__init__.py)
```

This PR fixes that by relying on the command line `--exclude` flag.

https://github.com/pypa/auditwheel/releases/tag/6.0.0